name: IsenecaWebMain

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

      
    - name: Setup flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'beta'

    - name: Enable Flutter Web
      run: flutter config --enable-web
    
    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-



    - name: Install dependencies
      run: flutter packages get

    - name: Build web
      run: flutter build web

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./build/web
